### ISSUE TITLE
TODO/FIXME Count 5

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-express#22]
- [ ] TODO: this call will currently send JSON/JSON-LD if it is preferred
       Commit: (2c49197) Add default error handler for requested JSON/JSON-LD.
       File:  [lib/express.js:245](https://github.com/digitalbazaar/bedrock-express/blob/master/lib/express.js#L245)
       Dave Longley commented 5 years ago

  - [ ] TODO: rate limit
       Commit: (39dba70) Update error logging.
       File:  [lib/index.js:214](https://github.com/digitalbazaar/bedrock-express/blob/master/lib/index.js#L214)
       David I. Lehn commented 7 months ago

  - [ ] TODO: check for 'critical' in exception chain and use that?
       Commit: (39dba70) Update error logging.
       File:  [lib/index.js:213](https://github.com/digitalbazaar/bedrock-express/blob/master/lib/index.js#L213)
       David I. Lehn commented 7 months ago

  - [ ] TODO: document why this is only set on a GET vs. other methods
       Commit: (2c49197) Add default error handler for requested JSON/JSON-LD.
       File:  [lib/express.js:196](https://github.com/digitalbazaar/bedrock-express/blob/master/lib/express.js#L196)
       Dave Longley commented 5 years ago

  - [ ] TODO: add mode to only log important server cause of exceptions
       Commit: (39dba70) Update error logging.
       File:  [lib/config.js:52](https://github.com/digitalbazaar/bedrock-express/blob/master/lib/config.js#L52)
       David I. Lehn commented 7 months ago

**Comment by JSAssassin** [comment]
Closing, opened individual issues of the items.
